displays:
  - name: DisplayPort-0
    workspaces: [9,0]
    randr_extra_options: "--above HDMI-A-0"
  - name: DisplayPort-1
    workspaces: [1,2,3]
    randr_extra_options: "--below DisplayPort-2"
  - name: DisplayPort-2
    workspaces: [7,8]
  - name: HDMI-A-0
    workspaces: [4,5,6]
    randr_extra_options: "--left-of DisplayPort-1"
